<?php

$defaultStates = array(
    array(
        'id' => 1,
        'name' => 'Вінницька область',
        'name_en' => 'Vinnytsia oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Тульчинський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Вінницький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Жмеринський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Хмільницький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Гайсинський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 2,
        'name' => 'Волинська область',
        'name_en' => 'Volyn oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Камінь-Каширський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Ковельський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Луцький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Володимир-Волинський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 3,
        'name' => 'Дніпропетровська область',
        'name_en' => 'Dnipropetrovsk oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Синельниківський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Павлоградський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Самарівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Дніпровський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Кам\'янський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Нікопольський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Криворізький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Новомосковський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(
            array(
                'name' => 'Червоногригорівська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Марганецька територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Нікопольська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Дніпровська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Криворізька територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Покровська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
    ),

    array(
        'id' => 4,
        'name' => 'Донецька область',
        'name_en' => 'Donetsk oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Кальміуський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Краматорський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Горлівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Бахмутський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Волноваський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Покровський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Маріупольський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Донецький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 5,
        'name' => 'Житомирська область',
        'name_en' => 'Zhytomyr oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Звягельський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Житомирський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Коростенський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Бердичівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 6,
        'name' => 'Закарпатська область',
        'name_en' => 'Zakarpattia oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Берегівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Мукачівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Ужгородський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Рахівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Тячівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Хустський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 7,
        'name' => 'Запорізька область',
        'name_en' => 'Zaporizhzhia oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Запорізький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Бердянський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Пологівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Василівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Мелітопольський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(
            array(
                'name' => 'Запорізька територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
    ),

    array(
        'id' => 8,
        'name' => 'Івано-Франківська область',
        'name_en' => 'Ivano-Frankivsk oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Верховинський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Калуський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Івано-Франківський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Коломийський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Косівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Надвірнянський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 9,
        'name' => 'Київська область',
        'name_en' => 'Kyiv oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Бориспільський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Броварський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Фастівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Обухівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Бучанський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Білоцерківський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Вишгородський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 10,
        'name' => 'Кіровоградська область',
        'name_en' => 'Kirovohrad oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Олександрійський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Кропивницький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Новоукраїнський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Голованівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(
            array(
                'name' => 'Світловодська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
    ),

    array(
        'id' => 11,
        'name' => 'Луганська область',
        'name_en' => 'Luhansk oblast',
        'alert' => true,
        'changed' => '2022-04-04 19:45:39',
        'reason' => '',
        'districts' => array(),
        'community' => array(),
    ),

    array(
        'id' => 12,
        'name' => 'Львівська область',
        'name_en' => 'Lviv oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Шептицький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Яворівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Львівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Золочівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Дрогобицький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Стрийський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Самбірський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Червоноградський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 13,
        'name' => 'Миколаївська область',
        'name_en' => 'Mykolaiv oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Вознесенський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Миколаївський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Баштанський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Первомайський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 14,
        'name' => 'Одеська область',
        'name_en' => 'Odesa oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Ізмаїльський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Роздільнянський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Березівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Болградський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Подільський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Одеський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 15,
        'name' => 'Полтавська область',
        'name_en' => 'Poltava oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Полтавський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Миргородський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Кременчуцький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Лубенський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 16,
        'name' => 'Рівненська область',
        'name_en' => 'Rivne oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Вараський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Рівненський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Сарненський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Дубенський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 17,
        'name' => 'Сумська область',
        'name_en' => 'Sumy oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Шосткинський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Сумський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Конотопський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Роменський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Охтирський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 18,
        'name' => 'Тернопільська область',
        'name_en' => 'Ternopil oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Тернопільський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Кременецький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Чортківський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 19,
        'name' => 'Харківська область',
        'name_en' => 'Kharkiv oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Богодухівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Харківський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Чугуївський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Берестинський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Лозівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Ізюмський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Куп\'янський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Красноградський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(
            array(
                'name' => 'Липецька територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Вовчанська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Вовчанська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Харківська територіальна громада',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
    ),

    array(
        'id' => 20,
        'name' => 'Херсонська область',
        'name_en' => 'Kherson oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Херсонський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Бериславський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Скадовський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Каховський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Генічеський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 21,
        'name' => 'Хмельницька область',
        'name_en' => 'Khmelnytskyi oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Шепетівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Хмельницький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Кам\'янець-Подільський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 22,
        'name' => 'Черкаська область',
        'name_en' => 'Cherkasy oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Черкаський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Золотоніський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Звенигородський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Уманський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 23,
        'name' => 'Чернівецька область',
        'name_en' => 'Chernivtsi oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Вижницький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Дністровський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Чернівецький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 24,
        'name' => 'Чернігівська область',
        'name_en' => 'Chernihiv oblast',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(
            array(
                'name' => 'Ніжинський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Прилуцький район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Корюківський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Новгород-Сіверський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
            array(
                'name' => 'Чернігівський район',
                'alert' => false,
                'changed' => '1970-01-01 03:00:00',
                'reason' => '',
            ),
        ),
        'community' => array(),
    ),

    array(
        'id' => 25,
        'name' => 'м. Київ',
        'name_en' => 'Kyiv',
        'alert' => false,
        'changed' => '1970-01-01 03:00:00',
        'reason' => '',
        'districts' => array(),
        'community' => array(),
    ),

    array(
        'id' => -1,
        'name' => 'Крим',
        'name_en' => 'Crimea',
        'alert' => true,
        'changed' => '2022-12-11 00:22:00',
        'reason' => '',
        'districts' => array(),
        'community' => array(),
    ),

    array(
        'id' => -2,
        'name' => 'Севастополь',
        'name_en' => 'Sevastopol',
        'alert' => true,
        'changed' => '2022-12-11 00:22:00',
        'reason' => '',
        'districts' => array(),
        'community' => array(),
    ),
);